apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-event-sinker
  name: kube-event-sinker-metrics
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9111
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: kube-event-sinker
